import { WebClient } from "@slack/web-api";

const slack = new WebClient(process.env.SLACK_BOT_TOKEN);
const channelId = process.env.SLACK_CHANNEL_ID as string;

export const sendCompetitorAlert = async (
  competitorName: string,
  summary: string,
  changes: string,
  strategicInsights: string,
  recommendations: string,
  significance: "low" | "medium" | "high"
): Promise<void> => {
  try {
    const significanceEmoji = {
      low: "🟡",
      medium: "🟠",
      high: "🔴",
    }[significance];

    const message = {
      channel: channelId,
      text: `${significanceEmoji} Competitor Alert: ${competitorName}`,
      blocks: [
        {
          type: "header",
          text: {
            type: "plain_text",
            text: `${significanceEmoji} COMPETITOR ALERT: ${competitorName.toUpperCase()}`,
          },
        },
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `*Significance:* ${significance.toUpperCase()}\n*Summary:*\n${summary}`,
          },
        },
        {
          type: "divider",
        },
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `*🔄 What Changed:*\n${changes}`,
          },
        },
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `*💡 Strategic Insights:*\n${strategicInsights}`,
          },
        },
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `*✅ Recommendations:*\n${
              Array.isArray(recommendations)
                ? recommendations.map((r: string) => `• ${r}`).join("\n")
                : recommendations
            }`,
          },
        },
        {
          type: "context",
          elements: [
            {
              type: "mrkdwn",
              text: `Generated by AI Competitor Intelligence System • ${new Date().toLocaleString()}`,
            },
          ],
        },
      ],
    };

    await slack.chat.postMessage(message);
    console.log(`✅ Slack alert sent for ${competitorName}`);
  } catch (error: any) {
    console.error(`❌ Slack alert failed:`, error.message);
  }
};